spring.application.name=aula19052026_api

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/aula19052026
spring.datasource.username=root
spring.datasource.password=
